// SPDX-License-Identifier: Apache-2.0
/* eslint-disable no-console */
/**
 * Verification of the linked-data proof suites we accept but never emit.
 *
 * The credentials driven through here were NOT produced by the code under test. They are
 * pinned fixtures generated by the reference implementations -- @digitalbazaar's
 * ed25519-signature-2020 and -2018 suites over jsonld-signatures 11.6.0, and
 * jsonld-signatures 5.2.0 for RsaSignature2018, the last release that bundled it. That
 * distinction is the whole point: a verifier checked only against its own signatures
 * proves it agrees with itself, which is exactly what an interoperability claim must not
 * rest on. If our canonicalization, our proof-options handling, or our reading of RFC 7797
 * differs from theirs by one byte, these fail.
 *
 * The negative cases matter as much as the positive ones. A verifier that accepts a real
 * credential is only useful if it also rejects a tampered one, the wrong key, a suite the
 * deployment did not opt into, and a context it has not pinned.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { createPublicKey, KeyObject } from 'node:crypto';
import { JWK } from 'jose';
import {
  verifyLdProof,
  AcceptedLdSuite,
  LEGACY_SUITES,
  MODERN_SUITE,
  LdDocument,
} from '../src/core/credentials/ld-suites';
import {
  registerPeerContext,
  clearPeerContexts,
} from '../src/core/credentials/jsonld/document-loader';
import {
  applyFederation,
  federatedVpTrustedIssuer,
  FederatedIssuer,
} from '../src/core/credentials/federation';
import { TrustedIssuer } from '../src/core/credentials/vc-verifier';
import { VpTrustedIssuer } from '../src/core/oid4vp/vp-verifier';
import { parseCountryConfig } from '../src/core/config/country-config';

let pass = 0;
let fail = 0;
function check(name: string, cond: boolean, detail?: string) {
  if (cond) {
    pass++;
    console.log(`  ✓ ${name}`);
  } else {
    fail++;
    console.log(`  ✗ ${name}${detail ? `\n      ${detail}` : ''}`);
  }
}

interface Vector {
  suite: AcceptedLdSuite;
  generatedBy: string;
  issuerDid: string;
  publicJwk: JWK;
  credential: LdDocument;
}

interface Fixture {
  peerContext: { url: string; document: unknown };
  vectors: Vector[];
}

const fixture: Fixture = JSON.parse(
  readFileSync(join(process.cwd(), 'test/fixtures/ld-proof-vectors.json'), 'utf8'),
);

const keyOf = (jwk: JWK): KeyObject => createPublicKey({ key: jwk as any, format: 'jwk' });

/** A structurally valid key of the same type that did not sign the credential. */
function foreignKeyFor(jwk: JWK): KeyObject {
  if (jwk.kty === 'OKP') {
    // Flip a bit in the key material rather than generating one: an Ed25519 public key is
    // any 32 bytes, so this stays a loadable key and isolates "wrong key" from "bad key".
    const raw = Buffer.from(jwk.x as string, 'base64url');
    raw[0] ^= 0xff;
    return keyOf({ ...jwk, x: raw.toString('base64url') });
  }
  const n = Buffer.from(jwk.n as string, 'base64url');
  n[8] ^= 0xff;
  return keyOf({ ...jwk, n: n.toString('base64url') });
}

async function main() {
  console.log('\nLinked-data proof suites (verify-only, cross-implementation vectors):\n');

  const allSuites: AcceptedLdSuite[] = [MODERN_SUITE, ...LEGACY_SUITES];

  // The peer defines its own credential terms; without its context pinned, canonicalization
  // cannot resolve them. Registering it is what a deployment does from federation config.
  registerPeerContext(fixture.peerContext.url, fixture.peerContext.document);

  for (const vector of fixture.vectors) {
    console.log(`  -- ${vector.suite} (${vector.generatedBy})`);
    const key = keyOf(vector.publicJwk);

    const ok = await verifyLdProof(vector.credential, [key], allSuites);
    check(`${vector.suite}: a credential from the reference implementation verifies`, ok.valid, ok.reason);
    check(`${vector.suite}: the verified suite is reported`, ok.suite === vector.suite);

    // Tamper: change a claim the signature covers.
    const tampered = JSON.parse(JSON.stringify(vector.credential)) as LdDocument;
    (tampered.credentialSubject as Record<string, unknown>).subnationalUnit = 'ZZ';
    const tamperedResult = await verifyLdProof(tampered, [key], allSuites);
    check(
      `${vector.suite}: a tampered claim does NOT verify`,
      !tamperedResult.valid && tamperedResult.reason === 'BAD_SIGNATURE',
      tamperedResult.reason,
    );

    // Tamper: change a proof option, which is covered by the same signature.
    const restamped = JSON.parse(JSON.stringify(vector.credential)) as LdDocument;
    (restamped.proof as Record<string, unknown>).created = '2020-01-01T00:00:00Z';
    const restampedResult = await verifyLdProof(restamped, [key], allSuites);
    check(
      `${vector.suite}: a rewritten proof option does NOT verify`,
      !restampedResult.valid,
      restampedResult.reason,
    );

    // Wrong key of the right type.
    const wrong = await verifyLdProof(vector.credential, [foreignKeyFor(vector.publicJwk)], allSuites);
    check(`${vector.suite}: another issuer's key does NOT verify`, !wrong.valid, wrong.reason);

    // Right key, but the deployment did not opt into this suite.
    const notAccepted = await verifyLdProof(vector.credential, [key], [MODERN_SUITE]);
    check(
      `${vector.suite}: rejected when the deployment has not accepted the suite`,
      !notAccepted.valid && notAccepted.reason === `SUITE_NOT_ACCEPTED:${vector.suite}`,
      notAccepted.reason,
    );

    // Key rotation: the signing key present among several still verifies.
    const rotated = await verifyLdProof(
      vector.credential,
      [foreignKeyFor(vector.publicJwk), key],
      allSuites,
    );
    check(`${vector.suite}: verifies when the signing key is one of several held`, rotated.valid);
  }

  // ---- Suite-level rejections ---------------------------------------------
  console.log('\n  -- rejections');
  const sample = fixture.vectors[0];
  const sampleKey = keyOf(sample.publicJwk);

  const noProof = await verifyLdProof(
    { ...sample.credential, proof: undefined },
    [sampleKey],
    allSuites,
  );
  check('a credential with no proof is rejected', !noProof.valid && noProof.reason === 'NO_PROOF');

  const unknownSuite = JSON.parse(JSON.stringify(sample.credential)) as LdDocument;
  (unknownSuite.proof as Record<string, unknown>).type = 'JcsEd25519Signature2020';
  const unknownResult = await verifyLdProof(unknownSuite, [sampleKey], allSuites);
  check(
    'an unrecognized suite is rejected rather than guessed at',
    !unknownResult.valid && unknownResult.reason?.startsWith('UNSUPPORTED_SUITE') === true,
    unknownResult.reason,
  );

  const wrongPurpose = JSON.parse(JSON.stringify(sample.credential)) as LdDocument;
  (wrongPurpose.proof as Record<string, unknown>).proofPurpose = 'authentication';
  const purposeResult = await verifyLdProof(wrongPurpose, [sampleKey], allSuites);
  check(
    'an authentication proof is not accepted as an assertion',
    !purposeResult.valid && purposeResult.reason?.startsWith('WRONG_PROOF_PURPOSE') === true,
    purposeResult.reason,
  );

  const proofSet = JSON.parse(JSON.stringify(sample.credential)) as LdDocument;
  proofSet.proof = [sample.credential.proof as any, sample.credential.proof as any];
  const proofSetResult = await verifyLdProof(proofSet, [sampleKey], allSuites);
  check(
    'a proof set is refused rather than half-checked',
    !proofSetResult.valid && proofSetResult.reason === 'PROOF_SET_UNSUPPORTED',
    proofSetResult.reason,
  );

  const noKeys = await verifyLdProof(sample.credential, [], allSuites);
  check('no keys means no verification', !noKeys.valid && noKeys.reason === 'NO_KEYS');

  // ---- The b64:false requirement (RFC 7797) --------------------------------
  const jwsVector = fixture.vectors.find((v) => v.suite === 'Ed25519Signature2018')!;
  const jwsKey = keyOf(jwsVector.publicJwk);
  const rewrittenHeader = JSON.parse(JSON.stringify(jwsVector.credential)) as LdDocument;
  const originalJws = (jwsVector.credential.proof as Record<string, unknown>).jws as string;
  const [, , sig] = originalJws.split('.');
  const attackerHeader = Buffer.from(JSON.stringify({ alg: 'EdDSA' })).toString('base64url');
  (rewrittenHeader.proof as Record<string, unknown>).jws = `${attackerHeader}..${sig}`;
  const headerResult = await verifyLdProof(rewrittenHeader, [jwsKey], allSuites);
  check(
    'a JWS header without b64:false is rejected',
    !headerResult.valid && headerResult.reason === 'JWS_B64_NOT_FALSE',
    headerResult.reason,
  );

  const noneAlg = JSON.parse(JSON.stringify(jwsVector.credential)) as LdDocument;
  const noneHeader = Buffer.from(
    JSON.stringify({ alg: 'none', b64: false, crit: ['b64'] }),
  ).toString('base64url');
  (noneAlg.proof as Record<string, unknown>).jws = `${noneHeader}..${sig}`;
  const noneResult = await verifyLdProof(noneAlg, [jwsKey], allSuites);
  check(
    'alg:none is rejected',
    !noneResult.valid && noneResult.reason === 'JWS_ALG_NOT_ACCEPTED:none',
    noneResult.reason,
  );

  // An RSA algorithm on an Ed25519 suite must not be accepted: the suite fixes the
  // algorithm, and letting the header choose it is letting the attacker choose it.
  const swappedAlg = JSON.parse(JSON.stringify(jwsVector.credential)) as LdDocument;
  const rsaHeader = Buffer.from(
    JSON.stringify({ alg: 'PS256', b64: false, crit: ['b64'] }),
  ).toString('base64url');
  (swappedAlg.proof as Record<string, unknown>).jws = `${rsaHeader}..${sig}`;
  const swappedResult = await verifyLdProof(swappedAlg, [jwsKey], allSuites);
  check(
    'an RSA alg on an Ed25519 suite is rejected',
    !swappedResult.valid && swappedResult.reason === 'JWS_ALG_NOT_ACCEPTED:PS256',
    swappedResult.reason,
  );

  // ---- The loader still refuses what is not pinned -------------------------
  clearPeerContexts();
  const unpinned = await verifyLdProof(sample.credential, [sampleKey], allSuites);
  check(
    'an unpinned peer context fails closed, and says so',
    !unpinned.valid && unpinned.reason?.startsWith('CANONICALIZATION_FAILED') === true,
    unpinned.reason,
  );

  let refusedOverride = false;
  try {
    registerPeerContext('https://www.w3.org/2018/credentials/v1', { '@context': {} });
  } catch {
    refusedOverride = true;
  }
  check('a peer cannot shadow a built-in context', refusedOverride);

  let refusedCollision = false;
  registerPeerContext(fixture.peerContext.url, fixture.peerContext.document);
  try {
    registerPeerContext(fixture.peerContext.url, { '@context': { residencyId: 'urn:evil' } });
  } catch {
    refusedCollision = true;
  }
  check('two peers cannot claim the same context URL with different content', refusedCollision);

  // ---- The wiring: config -> federation -> verifier ------------------------
  //
  // The suite verifier being correct is worth nothing if a deployment cannot actually
  // reach it from its config. This walks the real path: a peer declared in YAML-shaped
  // config, through applyFederation, to the trust entry the presentation verifier reads.
  console.log('\n  -- federation wiring');
  clearPeerContexts();
  const rsaVector = fixture.vectors.find((v) => v.suite === 'RsaSignature2018')!;
  const PEER_DID = 'did:web:id.peer.example.gov';
  const HOME_DID = 'did:web:id.katsina.gov.ng';

  const cfg = parseCountryConfig({
    countryCode: 'NG',
    countryName: 'Nigeria',
    foundational: {
      provider: 'MOCK',
      inputs: [{ key: 'nin', label: 'NIN' }],
      assuranceOnSuccess: 'verified',
    },
    residency: { minAssurance: 'verified', proofOfResidence: 'attestation' },
    credential: {
      issuerDid: HOME_DID,
      issuerName: 'Katsina',
      type: 'StateResidencyCredential',
      validityDays: 1095,
      context: ['https://www.w3.org/ns/credentials/v2'],
    },
    subnationalUnits: [{ code: 'KT', name: 'Katsina', parent: 'NG', level: 'state' }],
    federation: {
      trustedIssuers: [
        {
          did: PEER_DID,
          name: 'A MOSIP-era peer issuer',
          publicJwks: [{ ...rsaVector.publicJwk, kid: 'rsa-1' }],
          acceptedProofSuites: ['RsaSignature2018'],
          contexts: [fixture.peerContext],
        },
      ],
    },
  });
  check('a peer with an RSA key parses', cfg.federation.trustedIssuers[0].publicJwks[0].kty === 'RSA');
  check(
    'the peer\'s accepted suites and pinned contexts survive config parsing',
    cfg.federation.trustedIssuers[0].acceptedProofSuites[0] === 'RsaSignature2018' &&
      cfg.federation.trustedIssuers[0].contexts[0].url === fixture.peerContext.url,
  );

  const trust = new Map<string, TrustedIssuer>();
  const ldpTrust = new Map<string, VpTrustedIssuer>();
  applyFederation(trust, ldpTrust, cfg.federation.trustedIssuers as unknown as FederatedIssuer[]);

  const entry = ldpTrust.get(PEER_DID)!;
  check('federation builds a trust entry for the peer', !!entry);
  check(
    'the entry accepts the modern suite plus the peer\'s legacy one, and nothing else',
    JSON.stringify(entry.acceptedSuites) === JSON.stringify([MODERN_SUITE, 'RsaSignature2018']),
    JSON.stringify(entry.acceptedSuites),
  );

  const throughConfig = await verifyLdProof(
    rsaVector.credential,
    entry.publicKeyObjects,
    entry.acceptedSuites,
  );
  check(
    'the peer\'s credential verifies through the trust entry federation built',
    throughConfig.valid,
    throughConfig.reason,
  );

  // A second peer that did NOT opt into the legacy suite must not inherit it.
  const strictEntry = federatedVpTrustedIssuer({
    did: 'did:web:id.other.example',
    publicJwks: [{ ...rsaVector.publicJwk, kid: 'rsa-1' } as JWK],
  });
  const notInherited = await verifyLdProof(
    rsaVector.credential,
    strictEntry.publicKeyObjects,
    strictEntry.acceptedSuites,
  );
  check(
    'another peer does not inherit the legacy suite this one opted into',
    !notInherited.valid && notInherited.reason === 'SUITE_NOT_ACCEPTED:RsaSignature2018',
    notInherited.reason,
  );

  console.log(`\n== ${pass} passed, ${fail} failed ==\n`);
  process.exit(fail === 0 ? 0 : 1);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});